name: updateHost

on:
  push:
  schedule:
    - cron: '0 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Set up Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: fetch ip
        run: |
          python update.py
      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1
      - name: Commit and push if changed
        run: |
          git diff
          git config --global user.email "mkyrie05@gmail.com"
          git config --global user.name "action_bot"
          git add hosts.txt
          git commit -m "Github Action auto Updated"
          git push
        continue-on-error: true
      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: main
