name: updateHost

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

      - name: fetch ippython update.py
        run: |
          python update.py
      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1
      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
